services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - /etc/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - /etc/pgadmin/pgpassfile:/pgadmin4/pgpassfile:ro
    labels:
      com.centurylinklabs.watchtower.enable: "false"

volumes:
  pgadmin_data:
    name: pgadmin_data
