services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "5050:8978"

    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    labels:
      com.centurylinklabs.watchtower.enable: "false"

volumes:
  cloudbeaver_data:
    name: cloudbeaver_data
